name: phpstan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          ini-values: memory_limit=1G
          coverage: none
      - name: Install dependencies
        uses: ramsey/composer-install@v2
      - name: Run PHPStan
        run: vendor/bin/phpstan
