name: release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: -a --no-dev
          ignore-cache: yes
      - name: Archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: default-avatars.zip
          exclusions: composer.json composer.lock .editorconfig .git .github .gitignore .phpcs.xml.dist phpstan.neon.dist
      - name: Upload
        uses: AButler/upload-release-assets@v2.0
        with:
          files: default-avatars.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
